#\u7AEF\u53E3
server.port: 8003
#\u5FAE\u670D\u52A1\u540D
spring.application.name: feign-service
#\u6CE8\u518C\u5230eureka \u670D\u52A1\u5668
eureka.client.service-url.defaultZone: http://localhost:8000/eureka/
#\u6253\u5F00\u7194\u65AD\u5668\u529F\u80FD
feign:
  hystrix:
    enabled: true
