spring:
  cloud:
    config:
      server:
        git:
          password:
          #文件夹名
          searchPaths: config
          #仓库地址
          uri: https://github.com/cestlavie21/SpringCloudConfig/
          username:
      label: master
  application:
    name: config-server
server:
  port: 8888
#注册至eureka服务
eureka.client.service-url.defaultZone: http://localhost:8000/eureka/
