server:
  port: 8765
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      #consul 的ip 和 端口
      host: localhost
      port: 8500
      discovery:
        #设置微服务名
        serviceName: consul-consumer